allowBuilds:
  "@dal-go/dalgo@https://codeload.github.com/dal-go/dalgo-js/tar.gz/d170e9b640f14e558b05cfe82d99f2830ca6a287": true
  "@firebase/util@1.15.3": false
  "protobufjs@7.6.6": false
  "re2@1.26.1": false
  '@firebase/util': set this to true or false
  protobufjs: set this to true or false
  re2: set this to true or false
